In [20]:
import pandas as pd

In [21]:
df= pd.read_csv(r'C:/Users/suman/OneDrive/Desktop/csv/deliveries.csv')
print(df)

        match_id  inning                 batting_team  \
0              1       1          Sunrisers Hyderabad
1              1       1          Sunrisers Hyderabad
2              1       1          Sunrisers Hyderabad
3              1       1          Sunrisers Hyderabad
4              1       1          Sunrisers Hyderabad
...          ...     ...                          ...
150455       636       2  Royal Challengers Bangalore
150456       636       2  Royal Challengers Bangalore
150457       636       2  Royal Challengers Bangalore
150458       636       2  Royal Challengers Bangalore
150459       636       2  Royal Challengers Bangalore

                       bowling_team  over  ball        batsman    non_striker  \
0       Royal Challengers Bangalore     1     1      DA Warner       S Dhawan
1       Royal Challengers Bangalore     1     2      DA Warner       S Dhawan
2       Royal Challengers Bangalore     1     3      DA Warner       S Dhawan
3       Royal Challengers Bangalore     1     4      DA Warner       S Dhawan
4       Royal Challengers Bangalore     1     5      DA Warner       S Dhawan
...                             ...   ...   ...            ...            ...
150455          Sunrisers Hyderabad    20     2    Sachin Baby      CJ Jordan
150456          Sunrisers Hyderabad    20     3    Sachin Baby      CJ Jordan
150457          Sunrisers Hyderabad    20     4  Iqbal Abdulla    Sachin Baby
150458          Sunrisers Hyderabad    20     5    Sachin Baby  Iqbal Abdulla
150459          Sunrisers Hyderabad    20     6  Iqbal Abdulla    Sachin Baby

          bowler  is_super_over  ...  bye_runs  legbye_runs  noball_runs  \
0       TS Mills              0  ...         0            0            0
1       TS Mills              0  ...         0            0            0
2       TS Mills              0  ...         0            0            0
3       TS Mills              0  ...         0            0            0
4       TS Mills              0  ...         0            0            0
...          ...            ...  ...       ...          ...          ...
150455   B Kumar              0  ...         0            0            0
150456   B Kumar              0  ...         0            0            0
150457   B Kumar              0  ...         0            1            0
150458   B Kumar              0  ...         0            0            0
150459   B Kumar              0  ...         0            0            0

        penalty_runs  batsman_runs  extra_runs  total_runs  player_dismissed  \
0                  0             0           0           0               NaN
1                  0             0           0           0               NaN
2                  0             4           0           4               NaN
3                  0             0           0           0               NaN
4                  0             0           2           2               NaN
...              ...           ...         ...         ...               ...
150455             0             2           0           2               NaN
150456             0             0           0           0         CJ Jordan
150457             0             0           1           1               NaN
150458             0             1           0           1               NaN
150459             0             4           0           4               NaN

       dismissal_kind  fielder
0                 NaN      NaN
1                 NaN      NaN
2                 NaN      NaN
3                 NaN      NaN
4                 NaN      NaN
...               ...      ...
150455            NaN      NaN
150456        run out  NV Ojha
150457            NaN      NaN
150458            NaN      NaN
150459            NaN      NaN

[150460 rows x 21 columns]

In [25]:
df.head(3)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [24]:
df.tail(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [26]:
type(df)

pandas.core.frame.DataFrame

In [28]:
list(df.columns)

['match_id',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batsman',
 'non_striker',
 'bowler',
 'is_super_over',
 'wide_runs',
 'bye_runs',
 'legbye_runs',
 'noball_runs',
 'penalty_runs',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'player_dismissed',
 'dismissal_kind',
 'fielder']

In [30]:
df['batsman']
df['bowler']

0         TS Mills
1         TS Mills
2         TS Mills
3         TS Mills
4         TS Mills
            ...
150455     B Kumar
150456     B Kumar
150457     B Kumar
150458     B Kumar
150459     B Kumar
Name: bowler, Length: 150460, dtype: object

In [31]:
type(df['batsman'])

pandas.core.series.Series

In [33]:
list(df['batsman'])

['DA Warner',
 'DA Warner',
 'DA Warner',
 'DA Warner',
 'DA Warner',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'DA Warner',
 'DA Warner',
 'DA Warner',
 'DA Warner',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'MC Henriques',
 'S Dhawan',
 'S Dhawan',
 'MC Henriques',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'MC Henriques',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'MC Henriques',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'MC Henriques',
 'Yuvraj Singh',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'MC Henriques',
 'Yuvraj Singh',
 'DJ Hooda',
 'Yuvraj Singh',
 'DJ Hooda',
 'DJ Hooda',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'DJ Hooda',
 'DJ Hooda',
 'DJ Hooda',
 'DJ Hooda',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'DJ Hooda',
 'DJ Hooda',
 'DJ Hooda',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'Yuvraj Singh',
 'BCJ Cutting',
 'DJ Hooda',
 'BCJ Cutting',
 'DJ Hooda',
 'BCJ Cutting',
 'BCJ Cutting',
 'BCJ Cutting',
 'BCJ Cutting',
 'CH Gayle',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'Mandeep Singh',
 'Mandeep Singh',
 'CH Gayle',
 'Mandeep Singh',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'Mandeep Singh',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'TM Head',
 'TM Head',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'TM Head',
 'TM Head',
 'KM Jadhav',
 'TM Head',
 'TM Head',
 'TM Head',
 'KM Jadhav',
 'TM Head',
 'KM Jadhav',
 'TM Head',
 'KM Jadhav',
 'KM Jadhav',
 'KM Jadhav',
 'TM Head',
 'KM Jadhav',
 'KM Jadhav',
 'KM Jadhav',
 'TM Head',
 'TM Head',
 'KM Jadhav',
 'TM Head',
 'TM Head',
 'KM Jadhav',
 'TM Head',
 'KM Jadhav',
 'KM Jadhav',
 'TM Head',
 'KM Jadhav',
 'KM Jadhav',
 'KM Jadhav',
 'KM Jadhav',
 'TM Head',
 'TM Head',
 'KM Jadhav',
 'SR Watson',
 'TM Head',
 'TM Head',
 'SR Watson',
 'SR Watson',
 'TM Head',
 'TM Head',
 'SR Watson',
 'Sachin Baby',
 'Sachin Baby',
 'SR Watson',
 'Sachin Baby',
 'SR Watson',
 'STR Binny',
 'STR Binny',
 'SR Watson',
 'STR Binny',
 'STR Binny',
 'STR Binny',
 'SR Watson',
 'STR Binny',
 'STR Binny',
 'STR Binny',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'STR Binny',
 'SR Watson',
 'SR Watson',
 'STR Binny',
 'S Aravind',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'S Aravind',
 'YS Chahal',
 'YS Chahal',
 'TS Mills',
 'YS Chahal',
 'YS Chahal',
 'TS Mills',
 'TS Mills',
 'YS Chahal',
 'YS Chahal',
 'YS Chahal',
 'A Choudhary',
 'A Choudhary',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'JC Buttler',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'PA Patel',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'PA Patel',
 'PA Patel',
 'RG Sharma',
 'RG Sharma',
 'JC Buttler',
 'RG Sharma',
 'RG Sharma',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'JC Buttler',
 'RG Sharma',
 'RG Sharma',
 'RG Sharma',
 'N Rana',
 'JC Buttler',
 'AT Rayudu',
 'AT Rayudu',
 'N Rana',
 'AT Rayudu',
 'AT Rayudu',
 'N Rana',
 'N Rana',
 'AT Rayudu',
 'N Rana',
 'N Rana',
 'N Rana',
 'AT Rayudu',
 'N Rana',
 'N Rana',
 'AT Rayudu',
 'N Rana',
 'N Rana',
 'AT Rayudu',
 'AT Rayudu',
 'AT Rayudu',
 'N Rana',
 'AT Rayudu',
 'N Rana',
 'N Rana',
 'N Rana',
 'N Rana',
 'AT Rayudu',
 'KH Pandya',
 'N Rana',
 'KH Pandya',
 'N Rana',
 'N Rana',
 'KH Pandya',
 'N Rana',
 'N Rana',
 'KH Pandya',
 'N Rana',
 'N Rana',
 'KH Pandya',
 'N Rana',
 'KH Pandya',
 'N Rana',
 'KA Pollard',
 'N Rana',
 'KA Pollard',
 'KA Pollard',
 'KA Pollard',
 'KA Pollard',
 'N Rana',
 'N Rana',
 'KA Pollard',
 'KA Pollard',
 'KA Pollard',
 'N Rana',
 'HH Pandya',
 'HH Pandya',
 'KA Pollard',
 'KA Pollard',
 'HH Pandya',
 'KA Pollard',
 'HH Pandya',
 'KA Pollard',
 'KA Pollard',
 'HH Pandya',
 'HH Pandya',
 'KA Pollard',
 'KA Pollard',
 'HH Pandya',
 'HH Pandya',
 'KA Pollard',
 'HH Pandya',
 'KA Pollard',
 'TG Southee',
 'HH Pandya',
 'TG Southee',
 'TG Southee',
 'HH Pandya',
 'HH Pandya',
 'HH Pandya',
 'HH Pandya',
 'HH Pandya',
 'HH Pandya',
 'HH Pandya',
 'AM Rahane',
 'MA Agarwal',
 'MA Agarwal',
 'MA Agarwal',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'MA Agarwal',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'MA Agarwal',
 'MA Agarwal',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'SPD Smith',
 'BA Stokes',
 'BA Stokes',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'BA Stokes',
 'SPD Smith',
 'MS Dhoni',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'MS Dhoni',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'MS Dhoni',
 'MS Dhoni',
 'SPD Smith',
 'SPD Smith',
 'MS Dhoni',
 'SPD Smith',
 'MS Dhoni',
 'SPD Smith',
 'MS Dhoni',
 'MS Dhoni',
 'MS Dhoni',
 'MS Dhoni',
 'MS Dhoni',
 'SPD Smith',
 'MS Dhoni',
 'SPD Smith',
 'SPD Smith',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'BB McCullum',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'JJ Roy',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'JJ Roy',
 'BB McCullum',
 'JJ Roy',
 'SK Raina',
 'SK Raina',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'SK Raina',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'BB McCullum',
 'BB McCullum',
 'SK Raina',
 'BB McCullum',
 'BB McCullum',
 'BB McCullum',
 'SK Raina',
 'BB McCullum',
 'BB McCullum',
 'SK Raina',
 'BB McCullum',
 'SK Raina',
 'BB McCullum',
 'AJ Finch',
 'SK Raina',
 'AJ Finch',
 'AJ Finch',
 'SK Raina',
 'SK Raina',
 'AJ Finch',
 'AJ Finch',
 'AJ Finch',
 'SK Raina',
 'AJ Finch',
 'SK Raina',
 'AJ Finch',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'SK Raina',
 'KD Karthik',
 'KD Karthik',
 'KD Karthik',
 'SK Raina',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'G Gambhir',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'CA Lynn',
 'AM Rahane',
 'MA Agarwal',
 'MA Agarwal',
 'MA Agarwal',
 'MA Agarwal',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'AM Rahane',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'AM Rahane',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'SPD Smith',
 'BA Stokes',
 'SPD Smith',
 'BA Stokes',
 'SPD Smith',
 'SPD Smith',
 'SPD Smith',
 'BA Stokes',
 'MS Dhoni',
 'MS Dhoni',
 'MS Dhoni',
 'BA Stokes',
 'MS Dhoni',
 'BA Stokes',
 'MS Dhoni',
 'MS Dhoni',
 'BA Stokes',
 'MS Dhoni',
 'BA Stokes',
 'MS Dhoni',
 'MS Dhoni',
 'BA Stokes',
 'MS Dhoni',
 'MS Dhoni',
 'BA Stokes',
 'BA Stokes',
 'MS Dhoni',
 'MS Dhoni',
 'MK Tiwary',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'MK Tiwary',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'MK Tiwary',
 'MK Tiwary',
 'BA Stokes',
 'MK Tiwary',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'BA Stokes',
 'MK Tiwary',
 'BA Stokes',
 'DT Christian',
 'DT Christian',
 'MK Tiwary',
 'DT Christian',
 'MK Tiwary',
 'MK Tiwary',
 'DT Christian',
 'MK Tiwary',
 'MK Tiwary',
 'MK Tiwary',
 'DT Christian',
 'DT Christian',
 'DT Christian',
 'DT Christian',
 'MK Tiwary',
 'HM Amla',
 'HM Amla',
 'HM Amla',
 'HM Amla',
 'M Vohra',
 'HM Amla',
 'M Vohra',
 'M Vohra',
 'M Vohra',
 'M Vohra',
 'HM Amla',
 'M Vohra',
 'M Vohra',
 'HM Amla',
 'M Vohra',
 'M Vohra',
 'HM Amla',
 'M Vohra',
 'M Vohra',
 'HM Amla',
 'WP Saha',
 'WP Saha',
 'WP Saha',
 'WP Saha',
 'HM Amla',
 'HM Amla',
 'WP Saha',
 'HM Amla',
 'HM Amla',
 'WP Saha',
 'WP Saha',
 'WP Saha',
 'HM Amla',
 'WP Saha',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'HM Amla',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'HM Amla',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'AR Patel',
 'GJ Maxwell',
 'DA Miller',
 'GJ Maxwell',
 'DA Miller',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'DA Miller',
 'GJ Maxwell',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'DA Miller',
 'GJ Maxwell',
 'GJ Maxwell',
 'CH Gayle',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'SR Watson',
 'SR Watson',
 'CH Gayle',
 'CH Gayle',
 'CH Gayle',
 'SR Watson',
 'SR Watson',
 'CH Gayle',
 'CH Gayle',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'SR Watson',
 'Mandeep Singh',
 'Mandeep Singh',
 'SR Watson',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'Mandeep Singh',
 'KM Jadhav',
 'SR Watson',
 'KM Jadhav',
 ...]

In [35]:
df[['batsman']]

              batsman
0           DA Warner
1           DA Warner
2           DA Warner
3           DA Warner
4           DA Warner
...               ...
150455    Sachin Baby
150456    Sachin Baby
150457  Iqbal Abdulla
150458    Sachin Baby
150459  Iqbal Abdulla

[150460 rows x 1 columns]

In [36]:
type(df[['batsman']])

pandas.core.frame.DataFrame